import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
async function main() {
 await prisma.protocol.createMany({ data: [
  {slug:'movimento',name:'Prismma Movimento',shortName:'Dor persistente',title:'Dor persistente',shortDescription:'Para pessoas que convivem com dor persistente e desejam construir uma estratégia individualizada de cuidado.',description:'Um caminho de escuta, compreensão e cuidado para a dor persistente.',image:'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?auto=format&fit=crop&w=900&q=80',icon:'△',order:1},
  {slug:'equilibrio',name:'Prismma Equilíbrio',shortName:'Ansiedade e saúde do trabalhador',title:'Ansiedade e saúde do trabalhador',shortDescription:'Uma abordagem voltada à ansiedade, aos desafios da rotina e ao equilíbrio da vida cotidiana.',description:'Uma proposta de cuidado para ansiedade, rotina e trabalho.',image:'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=900&q=80',icon:'◌',order:2},
  {slug:'vital',name:'Prismma Vital',shortName:'Qualidade de vida e vitalidade',title:'Qualidade de vida e vitalidade',shortDescription:'Cuidado preventivo e integrado para quem busca mais qualidade de vida e vitalidade.',description:'Uma visão integrada e preventiva da saúde.',image:'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=900&q=80',icon:'✦',order:3}
 ] });
 await prisma.institutionalCard.createMany({data:[{icon:'⌁',title:'Avaliação individualizada',text:'Cada pessoa possui uma história, necessidades e contexto únicos.',order:1},{icon:'✦',title:'Base científica',text:'Decisões fundamentadas em conhecimento científico e experiência clínica.',order:2},{icon:'♡',title:'Cuidado integral',text:'Corpo, mente, contexto e estilo de vida em equilíbrio.',order:3},{icon:'◜',title:'Mais que tratamento',text:'Um processo de cuidado pensado para acompanhar sua evolução.',order:4}]});
 await prisma.faq.createMany({data:[['Como funciona a avaliação?','O primeiro encontro é dedicado à escuta e à compreensão da sua história, necessidades e contexto.'],['Quantas sessões são realizadas?','O acompanhamento pode ser estruturado em 8 sessões, conforme a avaliação individualizada.'],['O atendimento é presencial ou online?','O formato é definido de acordo com a disponibilidade e as necessidades de cada pessoa.'],['Onde acontecem os atendimentos?','As informações sobre local e modalidades são apresentadas no momento do agendamento.'],['É necessário levar exames?','Se você tiver exames disponíveis, eles podem contribuir para uma compreensão mais completa do seu contexto.'],['Como faço para agendar?','Entre em contato pelo WhatsApp para receber as orientações iniciais.']].map(([question,answer],order)=>({question,answer,order}))});
}
main().finally(()=>prisma.$disconnect());
